/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mwfdkebsxstomenvafmv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZmRrZWJzeHN0b21lbnZhZm12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk5NTcyMjgsImV4cCI6MjEwNTUzMzIyOH0.4QV--_1nDPYx7T6zwJKGIwvX1JAoKZQoU6Hyj6-sOBk"